# Generated by Django 5.1 on 2024-09-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.ImageField(null=True, upload_to="uploads\\posts"),
        ),
    ]
