# Generated by Django 5.1 on 2024-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_tags_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
