# Generated by Django 5.1 on 2024-09-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_store", "0005_author_alter_book_slug_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stret", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_store.address",
            ),
        ),
    ]
