# Generated by Django 5.1 on 2024-09-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_store", "0006_address_author_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="stret",
            new_name="street",
        ),
    ]
