# Generated by Django 5.1 on 2024-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_store", "0007_rename_stret_address_street"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address Entries"},
        ),
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_store.country"),
        ),
    ]
