# Generated by Django 5.1 on 2024-09-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_store", "0008_country_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
